name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Version
      id: vars
      run: |
        VERSION=$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        docker build -t errohit07/rohit:$VERSION .
        docker push errohit07/rohit:$VERSION

    - name: Deploy to Remote VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull errohit07/rohit:$VERSION
          docker stop Quiz_website || true
          docker rm Quiz_website || true
          docker run -d --name Quiz_website -p 9090:80 errohit07/rohit:$VERSION
          docker ps -a
          docker logs Quiz_website || true
